name: Publish to GitHub Pages
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compile with BookML
        id: bookml
        uses: vlmantova/bookml-action@v1
        with:
          release: false
          upload-aux-directory: false
          replace-bookml: true
      - name: Create tarball
        run: |
          tar -cvf "$RUNNER_TEMP"/docs.tar.gz -C "$RUNNER_TEMP"/auxdir/html/docs --exclude=./LaTeXML.cache .
      - name: Upload pages artifact
        uses: actions/upload-artifact@v6
        with:
          name: github-pages
          path: ${{ runner.temp }}/docs.tar.gz
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page-url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
